### ISSUE TITLE
playground.ru

### ISSUE THREAD

**Issue by HDark15** [XX-J/Direct-links-out#11]
Example:
`tzr://5762`

it should be:
`https://www.playground.ru/redirect/tzr/5762`

**Comment by XX-J** [comment]
Need link on page, where i may see "wrong"-type link(s).

**Comment by XX-J** [comment]
Я об этом и писал: Мне нужна ссылка на страницу, на которой я мог бы увидеть "неправильные" ссылки.
 Это нужно для подтверждения Ваших слов и для тестирования исправленного кода скрипта.
 После Вашего коммента я нашёл эти ссылки на главной и поработаю с ними...

**Comment by XX-J** [comment]
0253070
