### ISSUE TITLE
Twitter

### ISSUE THREAD

**Issue by privacyguy123** [XX-J/Direct-links-out#3]
Doesn't seem to be working on twitter properly - this script is doing it properly tho, maybe take a look? 

https://greasyfork.org/en/scripts/404632-twitter-direct/code

**Comment by XX-J** [comment]
"Direct links out" work on half cases - only on text links (for now). I planned to take up Twitter later.
 Thanks for link.

**Comment by XX-J** [comment]
@privacyguy123, please test with new version 3.4.
 If Content Security Policy in FireFox is buggy (i.e. script is not working), then put "security.csp.enable = false" in about:config, restart browser and test again.

**Comment by privacyguy123** [comment]
Nice, seems all good!

**Comment by privacyguy123** [comment]
This script now makes loading Twitter hang ...

**Comment by privacyguy123** [comment]
Bump

**Comment by XX-J** [comment]
> This script now makes loading Twitter hang ...

 When fast scrolling?

 On my side twitter work is normal, but i will try to fix it.

**Comment by privacyguy123** [comment]
Twitter page will not open at all with this script active for me - endless spinning circle.

**Comment by XX-J** [comment]
privacyguy123, you write:

> Nice, seems all good!

 But, after ten days:

> This script now makes loading Twitter hang ...

 What happend for this ten days? May be something with you browser? May be need clear browser cache?

 What browser and OS you use? Please, test with another browser: FireFox, Chrome...

**Comment by privacyguy123** [comment]
I imagine something in Twitter code changed - browser is latest FireFox, Windows 10

**Comment by privacyguy123** [comment]
Maybe this helps?

```Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src").```

**Comment by XX-J** [comment]
[XX-J](https://github.com/XX-J) commented [on 19 Aug](https://github.com/XX-J/Direct-links-out/issues/3#issuecomment-1220549157)

> ...If Content Security Policy in FireFox is buggy (i.e. script is not working), then put "security.csp.enable = false" in about:config, restart browser and test again.

 Or try [GreaseMonkey](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/). And try on Chrome.

**Comment by privacyguy123** [comment]
> 

```security.csp.enable``` removed long ago, not recommended to disable IMO

other script I linked works to fix Twitter links I guess

EDIT: broken in Greasemonkey too

**Comment by XX-J** [comment]
&nbsp; &nbsp;**I implemented second method.**

[Direct links out v4.7.1](https://www.mediafire.com/file/bau4d9rymjgf187/Direct_links_out_v4.7.1.user.js/file) - old, first method; &nbsp; [Direct links out v4.7.2](https://www.mediafire.com/file/4s630p4osnxzbph/Direct_links_out_v4.7.2.user.js/file) - second method.

&nbsp; &nbsp;Both methods works in next environment:

 Win7SP1 x64; Mozilla FireFox v78.13 ESR & **v102.6 ESR**;
 TamperMonkey v4.18.1; CSP is **not** disabled.

----------
 @privacyguy123, please test both methods and write:

 - results;
 - full environment, that you uses (like sample from me, above on text) + other scripts;
 - link(s) on page(s) Twitter's, where you have a problem(s).

----------
&nbsp; &nbsp;About [Twitter Direct](https://greasyfork.org/en/scripts/404632-twitter-direct/code):

 I newbie in JS (like in English too) and for me is hard to understand such JS. May be in future all cleared for me, and i implement logics "Twitter Direct" in "Direct links out".

**Comment by XX-J** [comment]
20eb1c0
