### ISSUE TITLE
Telegram and LinkedIn

### ISSUE THREAD

**Issue by alfuken** [XX-J/Direct-links-out#4]
For Telegram, links in messages sometimes point to `https://t.me/iv?url=<actual_link>`, for example, `https://t.me/iv?url=https://provereno.media/2022/07/30/govoril-li-bill-gates-chto-640-kb-hvatit-kazhdomu/`
Would be nice if that page would automatically redirect to the link target.

For LinkedIn, it's usually something like `https://www.linkedin.com/safety/go?url=https%3A%2F%2Fwww.hive.app%2F&trk=flagship-messaging-web&messageThreadUrn=urn%3Ali%3AmessagingThread%3A2-NjRj`

**Comment by XX-J** [comment]
Приведи, пожалуйста, страницы, на которых можно встретить такие ссылки.

**Comment by alfuken** [comment]
Хм. А вот с этим сложнее.

В первом случае ссылка генерируется в самом телеграме. Пример, допустим, вот: https://t.me/provereno_media/1132
Но если в веб-клиенте ещё возможно изменить ссылку на странице _до_ клика, то вот в нативных клиентах это уже не провернуть. Поэтому и упомянул что было бы здорово если бы страница `https://t.me/iv?url=<actual_link>` редиректила автоматически.

А вот с LI, к сожалению, пример не приведу, ибо это из личных сообщений, плюс там много фронтендовой магии, так что не уверен что это возможно. Но решение с авто-редиректом со страницы тоже могло бы сработать. Ситуация осложняется тем что LI, похоже, проверяет referrer при посещении такой страницы (например, как я указал в примере), так что пример если просто скопипастить - даже не откроется... :/ Так что даже не знаю можно ли тут что-либо сделать вообще.

**Comment by XX-J** [comment]
@alfuken, Спасибо за предложение с авторедиректами и проверь, пожалуйста:

 **1.** Авторедиректы ссылок из приложений (все возможные).

 **2.** Выпрямление ссылок в браузерных Telegram и LinkedIn.

**Comment by alfuken** [comment]
Работает, спасибо 👍
