### ISSUE TITLE
Incorrect Redirect on YouTube Short URL with Timecode

### ISSUE THREAD

**Issue by Kanzuke117** [XX-J/Direct-links-out#8]
Right clicking a playing video gives an option to Copy video URL at current time, which generates a link that looks like this:
https://youtu.be/_W0bSen8Qjg?t=77

This gets expanded when visited to a more normal format except that the timecode becomes the first parameter and a feature parameter is added:
https://www.youtube.com/watch?t=77&v=_W0bSen8Qjg&feature=youtu.be

Normally, the video should load and the final url fits the normal format:
https://www.youtube.com/watch?v=_W0bSen8Qjg&t=77s

However with Direct-links-out enabled, the final URL becomes this:
https://www.youtube.com/watch?v=&t=77s

This plays as an official error video https://youtu.be/9xp1XWmJ_Wo

**Comment by XX-J** [comment]
29f2fdd

**Comment by User486375** [comment]
@XX-J This is not fixed. https://youtu.be/_W0bSen8Qjg?t=77 is still redirected to https://www.youtube.com/watch?t=77 on 4.13

**Comment by XX-J** [comment]
71102c7
