### ISSUE TITLE
youtube.com

### ISSUE THREAD

**Issue by Daxy7** [XX-J/Direct-links-out#9]
**Need link on page, where i may see "wrong"-type link(s):**

`https://www.youtube.com/watch?v=ct2Td55rEUg`

 **Brief description** (if necessary):
 
Pinned comment of Police Activity contains bad referral which leads to 404 when visiting mentioned links.

`http://patreon.com/PoliceActivity&stzid=UgzUDSmOfzbZqWXgNxF4AaABAg`
what it should be:
`http://patreon.com/PoliceActivity`

**Comment by XX-J** [comment]
5fbe72e

**Comment by Daxy7** [comment]
in live chat youtube links other than yt (warning in private browsing/signed out)

```
https://www.youtube.com/redirect?event=live_chat&redir_token=QUFFLUhqbVRxOU9YRWxsXy1JM3pDTFFMUktldzNjLXB2Z3xBQ3Jtc0tsODVCcHgtQ0VvT0k0N3NZYkp6NWJlZjUtYTVvck1naFZ0WXdWS2RZaTV1X3Q1djhza3czQVlHNXprR1RoX1hfWkt0b1VscHdWU0xBekFObWgyWTBTLWxibXI0aURjRFlWTllxLUJZSGw2a3hZVFFiMA&q=https://gofundme.com/f/22oatsstrong
```


`https://gofundme.com/f/22oatsstrong`

**Comment by XX-J** [comment]
This link should be processed correctly.

 I have to reproduce situation, so give me a link on that video with chat.

**Comment by Daxy7** [comment]
Sorry, got it figured out. It was the HyperChat extension conflicting with modification.
Here's example page. Works fine when toggling off HC through button on the chat.
```
https://www.youtube.com/watch?v=QuUf_33kyg0
```
(searched gofundme live stream and sorted by live)
